### ISSUE TITLE
Compatible with Atom (or VIM)

### ISSUE THREAD

**Issue by ericop** [nondev/non-sublime#1]
I actually use VIM ( https://en.wikipedia.org/wiki/Vim_(text_editor) ), and my next choice is Atom ( https://atom.io/) . Have you thought about having auto-completion for these as well?

**Comment by ericop** [comment]
Also, let me just generally say, this whole project, Yae, seems mega awesome!

**Comment by deathbeam** [comment]
I thought about adding support for Atom, but they do not have such easy method to add autocompletion like Sublime. And thanks, but Yae will be even hundred times better soon ;) I am going to rewrite backend in C# and Mono, so cross-platform support will be even better :)
